import { createSlice } from "@reduxjs/toolkit";


const counterSlice=createSlice({
    name:'counter',         //slice name

    initialState:{          //state define
        value:0      
    },
    
    reducers:{   // here logic define in reducer function

        //increment 
        increment:state=>{
            state.value = state.value + 1;
        },

        //decrement
        decrement(state){
          state.value -= 1;
        },

        //increment with payload amount
        incrementByAmount:(state,action)=>{
            state.value += action.payload;
        },

        //decrement with payload amount
        decrementByAmount:(state,action)=>{
            state.value -= action.payload;
        },

        //clear all
        clearAll:(state)=>{
            state.value = 0;
        }

    }
})

//^ Action creators are automatic generated by createSlice based on same name of Reducer fun
export const{increment, decrement, incrementByAmount, decrementByAmount, clearAll} = counterSlice.actions;

// default export  which basically import in Rtk_store where all multiple reducer pass  , so there any name use (e.g counterReducer) 
export default counterSlice.reducer;            


